[[linter]]
code = "CLANGFORMAT"
include_patterns = [
    "comms/torchcomms/**/*.hpp",
    "comms/torchcomms/**/*.cpp",
]
exclude_patterns = []
init_command = [
    "python3",
    "tools/linter/adapters/pip_init.py",
    "--dry-run={{DRYRUN}}",
    "clang-format==21.1.2",
]
command = [
    "python3",
    "tools/linter/adapters/clangformat_linter.py",
    "--binary=.lintbin/clang-format",
    "--",
    "@{{PATHSFILE}}",
]
is_formatter = true

[[linter]]
code = "PYREFLY"
include_patterns = [
    "comms/torchcomms/**/*.py",
    "comms/torchcomms/**/*.pyi",
]
exclude_patterns = []
command = [
    "python3",
    "tools/linter/adapters/pyrefly_linter.py",
    "--config=pyrefly.toml",
]
init_command = [
    "python3",
    "tools/linter/adapters/pip_init.py",
    "--dry-run={{DRYRUN}}",
    "pyrefly==0.36.2",
]
